version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: db
        ports:
            - 3306:3306
        volumes:
            - ./storage/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: text_finetune_poc
            MYSQL_USER: localhost
            MYSQL_PASSWORD: root
        restart: always
